// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let array = [1,2];
let n =0;
let sum = array[1];
while (array[array.length - 1] < 4000000){
    newNum = array[n] + array[n+1];
    array.push(newNum);
    if (newNum % 2 === 0){
        sum += newNum;
    }
    n += 1;
}
console.log(sum);