# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?
require "prime"
num = 1
triangle_num =1
active=true
while active
    num +=1
    triangle_num +=num 
    # 28's prime_division is [2,2],[7,1]  => [4,2,1], [7,1] => 3*2 = 6 divisors
    if triangle_num.prime_division.map{|arr| arr[1]+1}.inject(:*) > 500
        puts triangle_num
        active = false
    end 
end

